[font]
size=14.0
normal={family="JetBrainsMono Nerd Font", style="Medium"}
bold={family="JetBrainsMono Nerd Font", style="Bold"}

[window]
padding={x=15, y=15}
opacity=1.0
startup_mode="Maximized"

[scrolling]
history=10000
multiplier=5

# Ayu Mirage Theme
[colors.primary]
background="#1f2430"
foreground="#cbccc6"
bright_foreground="#f28779"

[colors.normal]
black="#212733"
red="#f08778"
green="#53bf97"
yellow="#fdcc60"
blue="#60b8d6" 
magenta="#ec7171"
cyan="#98e6ca"
white="#fafafa"

[colors.bright]
black="#686868"
red="#f58c7d"
green="#58c49c"
yellow="#ffd165"
blue="#65bddb"
magenta="#f17676"
cyan="#9debcf"
white="#ffffff"
